### ISSUE TITLE
IndexGrantDetailsAccountUsage fails with null source parameter

### ISSUE THREAD

**Issue by GregBowmanMoO** [Snowflake-Labs/sfgrantreport#10]
Application execution took 00:00:00.4310316 (431 ms)
req86287@C02YQ0GFLVCF SFGrantReport.osx.2021.4.2.0 % ./SFGrantReport -i account_usage -o ~/SFGoutput -d
Snowflake Grant Report Version 2021.4.2.0
Executing ProgramOptions: ConnectionName='' OutputFolderPath='/Users/req86287/SFGoutput' DeletePreviousReportOutput='True' InputFolderPath='account_usage' ProcessSequentially='False'
Clearing output folder /Users/req86287/SFGoutput
Creating output folder /Users/req86287/SFGoutput
New report /Users/req86287/SFGoutput/Snowflake.GrantReport.json
Starting job from status ExtractCurrentContext(100)
Executing job step ExtractCurrentContext(100)
Connection name is empty. Skipping this step
Executing job step ExtractUsersRolesGrants(101)
Connection name is empty. Skipping this step
Executing job step IndexUserDetails(200)
Connection name is empty. Skipping this step
Executing job step IndexGrantDetails(201)
Connection name is empty. Skipping this step
Executing job step IndexGrantDetailsAccountUsage(202)
Input Folder Path is not empty. Will execute
IndexGrantDetailsAccountUsage(202): Starting
Process Grants ON and TO
Process Grants OF Users
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Snowflake.GrantReport.ProcessingSteps.IndexGrantDetailsAccountUsage.Execute(ProgramOptions programOptions)
IndexGrantDetailsAccountUsage(202): total duration 00:00:00.0731931 (73 ms)
Application execution took 00:00:02.5738926 (2573 ms)

**Comment by sfc-gh-dodievich** [comment]
Fixed in https://github.com/Snowflake-Labs/sfgrantreport/releases/tag/2021.5.17.0
