### ISSUE TITLE
how to connect when account requires --authenticator externalbrowser

### ISSUE THREAD

**Issue by seecoolguy** [Snowflake-Labs/sfgrantreport#12]
when I login via SnowSql my -c requires the parameter:  --authenticator externalbrowser, how do I add this to a connection for sfgrantreport?  Currently I'm prompted for my pwd but this process does not work for my sso account.

**Comment by sfc-gh-dodievich** [comment]
Sorry for not noticing this until now. This is a question for SnowSQL documentation. You must configure named connection. https://docs.snowflake.com/en/user-guide/snowsql-start.html#connecting-to-snowflake-using-a-named-connection. Once you have that, you'll be prompted for your SSO on every step of this tool and will have to provide your creds each time.
