### ISSUE TITLE
snowsql substitution variables are not enabled

### ISSUE THREAD

**Issue by sfc-gh-jdacosta** [Snowflake-Labs/sfgrantreport#9]
sfgrantreport/Snowhouse/SnowhouseGrantsToRoles.sql

snowsql -c snowhouse -f "SnowhouseGrantsToUsers.sql" -D DEPLOYMENT='va' -D ACCOUNT_ID=8289 -o output_format=csv -o header=true -o timing=false -o friendly=false > "GRANTS_TO_ROLES.csv"

001003 (42000): SQL compilation error:
syntax error line 27 at position 22 unexpected '&'.
syntax error line 28 at position 27 unexpected '&'.
syntax error line 31 at position 27 unexpected '&'.
syntax error line 34 at position 27 unexpected '&'.
syntax error line 37 at position 80 unexpected '&'.

--> fix is to add  -o variable_substitution=true, in addition, i did not have a default warehouse, so adding in use of the warehouse & or role, may be beneficial.

snowsql -w snowhouse -c snowhouse -f "SnowhouseGrantsToUsers.sql" -D DEPLOYMENT='va' -D ACCOUNT_ID=8289 -o output_format=csv -o header=true -o timing=false -o friendly=false -o variable_substitution=true > "GRANTS_TO_ROLES.csv"

**Comment by sfc-gh-dodievich** [comment]
Interesting. I have variable substitution on permanently, but you are right, this may not be true for others.
That is a superb suggestion. 
I'll add this right now.

**Comment by sfc-gh-dodievich** [comment]
Fixed in https://github.com/Snowflake-Labs/sfgrantreport/releases/tag/2021.5.17.0
